export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GETPRODUCTS_BEGIN = "GETPRODUCTS_BEGIN";
export const GETPRODUCTS_SUCCESS = "GETPRODUCTS_SUCCESS";
export const GETPRODUCTS_ERROR = "GETPRODUCTS_ERROR";
