export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GETPRODUCTS_BEGIN = "GETPRODUCTS_BEGIN";
export const GETPRODUCTS_SUCCESS = "GETPRODUCTS_SUCCESS";
export const GETPRODUCTS_ERROR = "GETPRODUCTS_ERROR";
export const GETPRODUCT_BEGIN = "GETPRODUCT_BEGIN";
export const GETPRODUCT_SUCCESS = "GETPRODUCT_SUCCESS";
export const GETPRODUCT_ERROR = "GETPRODUCT_ERROR";
